name: Publish VS Code Extension

on:
  workflow_dispatch:
  push:
    tags:
      - 'extension-v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd vscode-extension
          npm ci
          npm run build
      - name: Install vsce
        run: npm install -g vsce
      - name: Publish to Marketplace
        run: vsce publish -p ${{ secrets.VSCE_TOKEN }}
        working-directory: vscode-extension
